--------------------------------------------------------------------------------
----------------------- T A B L A S --------------------------------------------
--------------------------------------------------------------------------------
----------<> MAESTROS
-- 01 Tabla: person (persona)
CREATE TABLE person (
    id integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
    rol_person char(1),
    type_document char(3),
    number_document varchar2(20),
    names varchar2(60),
    last_name varchar2(90),
    cell_phone char(9),
    email varchar2(80),
    birthdate date,
    salary number(8,2),
    seller_rol varchar2(20),
    seller_user varchar2(100),
    seller_password varchar2(130),
    active char(1) DEFAULT 'A',
    CONSTRAINT person_pk PRIMARY KEY (id),
    CONSTRAINT type_document_ck CHECK (type_document IN ('DNI', 'CNE')),
    CONSTRAINT number_document_uk UNIQUE (number_document),
    CONSTRAINT email_ck CHECK (REGEXP_LIKE(email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$'))
);

-- 02 Tabla: supplier (proveedor)
CREATE TABLE supplier (
    id integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ruc char(11),
    name_company varchar2(90),
    type_document char(3),
    number_document varchar2(20),
    names varchar2(60),
    last_name varchar2(80),
    email varchar2(90),
    cell_phone char(9),
    active char(1) DEFAULT 'A',
    CONSTRAINT supplier_pk PRIMARY KEY (id),
    CONSTRAINT type_document_supplier_ck CHECK (type_document IN ('DNI', 'CNE')),
    CONSTRAINT number_document_supplier_uk UNIQUE (number_document),
    CONSTRAINT email_supplier_ck CHECK (REGEXP_LIKE(email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$'))
);

-- 03 Tabla: category_product (categoría producto)
CREATE TABLE category_product (
    id integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name varchar2(60),
    description varchar2(90),
    active char(1) DEFAULT 'A',
    CONSTRAINT category_product_pk PRIMARY KEY (id)
);

-- 04 Tabla: product (producto)
CREATE TABLE product (
    id integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
    code char(4) UNIQUE,
    name varchar2(60),
    description varchar2(200),
    category_product_id integer,
    price_unit number(8,2),
    unit_sale varchar2(10),
    date_expiry date,
    stock number(8,2),
    active char(1) DEFAULT 'A',
    CONSTRAINT product_pk PRIMARY KEY (id),
    CONSTRAINT unit_sale_options CHECK (unit_sale IN ('Unidad', 'Kilo'))
);


-- 05 Tabla: payment_method (método de pago)
CREATE TABLE payment_method (
    id integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name varchar2(90),
    description varchar2(100),
    active char(1) DEFAULT 'A',
    CONSTRAINT payment_method_pk PRIMARY KEY (id)
);

----------<> TRANSACCIONAL

-- 06 Tabla: purchase (compra)
CREATE TABLE purchase (
    id integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
    supplier_id integer,
    seller_id integer,
    payment_method_id integer,
    total_purchase number(8,2),
    date_time DATE DEFAULT SYSDATE,
    active char(1) DEFAULT 'A',
    CONSTRAINT purchase_pk PRIMARY KEY (id)
);

-- 07 Tabla: purchase_detail (detalle de compra)
CREATE TABLE purchase_detail (
    id integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
    purchase_id integer,
    product_id integer,
    price_unit number(8,2),
    amount number(8,2),
    subtotal_purchase number(8,2),
    CONSTRAINT purchase_detail_pk PRIMARY KEY (id)
);

-- 08 Tabla: sale (venta)
CREATE TABLE sale (
    id integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
    seller_id integer,
    client_id integer,
    payment_method_id integer,
    total_sale number(8,2),
    date_time DATE DEFAULT SYSDATE,
    active char(1) DEFAULT 'A',
    CONSTRAINT sale_pk PRIMARY KEY (id)
);

-- 09 Tabla: sale_detail (detalle de venta)
CREATE TABLE sale_detail (
    id integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
    sale_id integer,
    product_id integer,
    amount number(8,2),
    subtotal_sale number(8,2),
    CONSTRAINT sale_detail_pk PRIMARY KEY (id)
);


CREATE TABLE reserva (
    id integer GENERATED BY DEFAULT ON NULL AS IDENTITY,          -- ID único para la reserva
    seller_id integer NOT NULL,                                   -- ID del vendedor
    client_id integer NOT NULL,                                   -- ID del cliente que realiza la reserva
    payment_method_id integer NOT NULL,                           -- ID del método de pago utilizado
    fecha_reserva TIMESTAMP NOT NULL,                             -- Fecha y hora en la que se hace la reserva                          -- Cantidad del producto reservado
    estado_reserva varchar2(20) CHECK (estado_reserva IN ('pendiente', 'confirmada', 'cancelada')) NOT NULL,  -- Estado de la reserva
    comentario varchar2(200),                                     -- Comentario opcional sobre la reserva
    total_reserva decimal(10, 2) NOT NULL,                        -- Total de la reserva
    CONSTRAINT reserva_pk PRIMARY KEY (id),                       -- Llave primaria
    CONSTRAINT reserva_seller_fk FOREIGN KEY (seller_id) REFERENCES person (id),   -- Relación con la tabla person (vendedor)
    CONSTRAINT reserva_client_fk FOREIGN KEY (client_id) REFERENCES person (id),   -- Relación con la tabla person (cliente)
    CONSTRAINT reserva_payment_method_fk FOREIGN KEY (payment_method_id) REFERENCES payment_method (id) -- Relación con la tabla payment_method
);




CREATE TABLE reserva_detalle (
    id integer GENERATED BY DEFAULT ON NULL AS IDENTITY,             -- ID único para el detalle de la reserva
    reserva_id integer NOT NULL,                                     -- ID de la reserva asociada
    product_id integer NOT NULL,                                     -- ID del producto reservado
    cantidad integer NOT NULL,                                       -- Cantidad del producto reservado
    precio_unitario number(8,2) NOT NULL,                            -- Precio unitario del producto en el momento de la reserva
    subtotal number(8,2) NOT NULL,                                   -- Subtotal (cantidad * precio unitario)
    CONSTRAINT reserva_detalle_pk PRIMARY KEY (id),                  -- Llave primaria
    CONSTRAINT reserva_detalle_reserva_fk FOREIGN KEY (reserva_id) REFERENCES reserva (id),  -- Relación con la tabla reserva
    CONSTRAINT reserva_detalle_product_fk FOREIGN KEY (product_id) REFERENCES product (id)   -- Relación con la tabla product
);


--------------------------------------------------------------------------------
---------------------------- R E L A C I O N E S -------------------------------
--------------------------------------------------------------------------------

-- 1. Una categoría de producto puede estar en uno o varios productos
ALTER TABLE product ADD CONSTRAINT product_category_product
    FOREIGN KEY (category_product_id)
    REFERENCES category_product (id);

-- 2. Una persona (cliente) puede estar en una o muchas ventas
ALTER TABLE sale ADD CONSTRAINT sale_client
    FOREIGN KEY (client_id)
    REFERENCES person (id);
   
-- 3. Una persona (vendedor) puede realizar una o muchas ventas
ALTER TABLE sale ADD CONSTRAINT sale_seller
    FOREIGN KEY (seller_id)
    REFERENCES person (id);
    
-- 4. Un método de pago puede estar en una o muchas ventas
ALTER TABLE sale ADD CONSTRAINT sale_payment_method
    FOREIGN KEY (payment_method_id)
    REFERENCES payment_method (id);

-- 5. Un proveedor puede realizar una o varias compras
ALTER TABLE purchase ADD CONSTRAINT purchase_supplier
    FOREIGN KEY (supplier_id)
    REFERENCES supplier (id);

-- 6. Una persona (vendedor) puede realizar una o muchas compras
ALTER TABLE purchase ADD CONSTRAINT purchase_seller
    FOREIGN KEY (seller_id)
    REFERENCES person (id);
    
-- 7. Una compra puede tener uno o muchos detalles de compra
ALTER TABLE purchase_detail ADD CONSTRAINT purchase_detail_purchase
    FOREIGN KEY (purchase_id)
    REFERENCES purchase (id);

-- 8. Un método de pago puede estar en una o muchas compras
ALTER TABLE purchase ADD CONSTRAINT purchase_payment_method
    FOREIGN KEY (payment_method_id)
    REFERENCES payment_method (id);

-- 9. Un producto puede estar en uno o muchos detalles de compra
ALTER TABLE purchase_detail ADD CONSTRAINT purchase_detail_product
    FOREIGN KEY (product_id)
    REFERENCES product (id);
    
-- 10. Una venta puede tener uno o muchos detalles de venta
ALTER TABLE sale_detail ADD CONSTRAINT sale_detail_sale
    FOREIGN KEY (sale_id)
    REFERENCES sale (id);
    
-- 11. Un producto puede estar en uno o muchos detalles de venta
ALTER TABLE sale_detail ADD CONSTRAINT sale_detail_product
    FOREIGN KEY (product_id)
    REFERENCES product (id);



--Si no se cambia la fecha de la hora--
ALTER SESSION SET TIME_ZONE = 'America/Lima';
SELECT SESSIONTIMEZONE FROM dual;
